# 异常

![java异常处理](/Users/qiruiliu/Desktop/mashibingEdu/javaLearned/java零基础课程笔记/java异常处理.png)

>    异常处理的方式：
>        1、捕获异常
>            try{代码逻辑}catch(Exception e){异常处理逻辑} ==e.printStackTrace();==
>
> ​           try{代码逻辑}catch(具体的异常Exception e){异常处理逻辑}catch(具体的异常)：
> ​                 可以针对每一种具体的异常做相应的更丰富的处理
>
> ​			注意：当使用多重的catch的时候一定要注意相关异常的顺序，将子类放在最前面的catch，父类放在后面的catch

在程序运行过程中，如果处理异常的部分包含finally的处理，那么无论代码是否发生异常，finally中的代码总会执行

finally包含哪些处理逻辑？
1、IO流的关闭操作一般设置在finally中
2、数据库的连接关闭操作设置在finally中

throws:声明异常
* 在异常情况出现的时候，可以使用try...catch...finally的方式对异常进行处理，除此之外，可以将异常向外抛出，由外部的进行处理

  1. 在方法调用过程中，可以存在N多个方法之间的调用，此时假如每个方法中都包含了异常情况，那么就需要在每个方法中都进行try...catch，另外一种比较简单的方式，就是在方法的最外层调用处理一次即可，==使用throws的方法，对所有执行过程中的所有方法出现的异常进行统一集中处理==

  2. 如何判断是使用throws还是使用try...catch..

     最稳妥的方式是在每个方法中都进行异常的处理

     偷懒的方式是判断在整个调用的过程中，外层的调用方法是否有对异常的处理，如果有，直接使用throws, 如果没有，那么就要使用try...catch...

```java
public class Excepton2 {
    public static void main(String[] args) {
        try {
            show();
        } catch (GenderException e) {
            e.printStackTrace();
        }
        System.out.println("hehe");
    }

    public static void show() throws GenderException{
        String gender = "1234";
        if (gender.equals("man")){
            System.out.println("man");
        }else if(gender.equals("woman")){
            System.out.println("woman");
        }else{
            throw new GenderException("gender is wrong");
        }
    }

    public static void test1() throws Exception{
        System.out.println(1/0);
    }
    public static void test2() throws Exception {
        test1();
        System.out.println(100/0);
    }
    public static void test3() throws Exception{
        test2();
    }
    public static void test4() throws Exception{
        test3();
    }
}
```